import oracledb
import configparser

# 1. Načteme údaje z config.ini (abychom nemuseli nic vypisovat ručně)
config = configparser.ConfigParser()
config.read('config.ini')

try:
    user = config['database']['user']
    pwd = config['database']['password']
    dsn = config['database']['dsn']  # Použijeme DSN, co jsme tam přidali

    print(f"Připojuji se jako {user}...")
    connection = oracledb.connect(user=user, password=pwd, dsn=dsn)
    cursor = connection.cursor()
    print("--- PŘIPOJENO ---")

    # 2. Tvůj SQL skript (rozdělený na příkazy)
    # Poznámka: Python neumí pustit celý skript naráz, musíme to posílat po jednom.
    sql_commands = [
        """CREATE TABLE warehouses (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            location VARCHAR2(100) NOT NULL,
            capacity NUMBER(10, 2) NOT NULL
        )""",
        """CREATE TABLE clients (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_name VARCHAR2(150) NOT NULL,
            contact_email VARCHAR2(100),
            contract_signed_date DATE NOT NULL,
            credit_balance NUMBER(12, 2) DEFAULT 0
        )""",
        """CREATE TABLE materials (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100) NOT NULL,
            price_per_kg NUMBER(10, 2) NOT NULL, 
            hazard_level VARCHAR2(20) NOT NULL,
            CONSTRAINT chk_hazard CHECK (hazard_level IN ('Low', 'Medium', 'High', 'Death')),
            is_active NUMBER(1) DEFAULT 1 NOT NULL,
            CONSTRAINT chk_active CHECK (is_active IN (0, 1))
        )""",
        """CREATE TABLE orders (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            client_id NUMBER NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR2(20) DEFAULT 'NEW',
            CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES clients(id),
            CONSTRAINT chk_status CHECK (status IN ('NEW', 'PAID', 'SHIPPED', 'CANCELLED'))
        )""",
        """CREATE TABLE order_items (
            order_id NUMBER NOT NULL,
            material_id NUMBER NOT NULL,
            quantity NUMBER(10, 2) NOT NULL,
            CONSTRAINT pk_order_items PRIMARY KEY (order_id, material_id),
            CONSTRAINT fk_items_order FOREIGN KEY (order_id) REFERENCES orders(id),
            CONSTRAINT fk_items_material FOREIGN KEY (material_id) REFERENCES materials(id)
        )""",
        """CREATE OR REPLACE VIEW v_active_pricelist AS
            SELECT name, hazard_level, price_per_kg
            FROM materials
            WHERE is_active = 1""",
        """CREATE OR REPLACE VIEW v_client_spending AS
            SELECT c.company_name, COUNT(o.id) as total_orders
            FROM clients c
            LEFT JOIN orders o ON c.id = o.client_id
            GROUP BY c.company_name""",
        
        # Vkládání dat
        "INSERT INTO warehouses (location, capacity) VALUES ('Sklad A - Černobyl', 5000)",
        "INSERT INTO warehouses (location, capacity) VALUES ('Sklad B - Fukušima', 2000)",
        "INSERT INTO warehouses (location, capacity) VALUES ('Sklad C - Springfield', 1000)",

        "INSERT INTO clients (company_name, contact_email, contract_signed_date, credit_balance) VALUES ('Umbrella Corp', 'virus@umbrella.com', TO_DATE('2023-01-15', 'YYYY-MM-DD'), 50000)",
        "INSERT INTO clients (company_name, contact_email, contract_signed_date, credit_balance) VALUES ('Massive Dynamic', 'bell@massive.com', TO_DATE('2023-05-20', 'YYYY-MM-DD'), 12000)",
        "INSERT INTO clients (company_name, contact_email, contract_signed_date, credit_balance) VALUES ('Aperture Science', 'glados@aperture.com', TO_DATE('2024-02-01', 'YYYY-MM-DD'), 0)",

        "INSERT INTO materials (name, price_per_kg, hazard_level, is_active) VALUES ('Vyhořelé palivo', 150.50, 'Death', 1)",
        "INSERT INTO materials (name, price_per_kg, hazard_level, is_active) VALUES ('Azbestová drť', 25.00, 'Medium', 1)",
        "INSERT INTO materials (name, price_per_kg, hazard_level, is_active) VALUES ('Lékařský odpad', 45.00, 'High', 1)",
        "INSERT INTO materials (name, price_per_kg, hazard_level, is_active) VALUES ('Staré tonery', 5.00, 'Low', 0)",

        "INSERT INTO orders (client_id, status) VALUES (1, 'NEW')",
        "INSERT INTO orders (client_id, status) VALUES (1, 'PAID')",
        "INSERT INTO orders (client_id, status) VALUES (2, 'NEW')",

        "INSERT INTO order_items (order_id, material_id, quantity) VALUES (1, 2, 100)",
        "INSERT INTO order_items (order_id, material_id, quantity) VALUES (1, 1, 50)",
        "INSERT INTO order_items (order_id, material_id, quantity) VALUES (2, 3, 200)",
    ]

    print("Vytvářím tabulky a vkládám data...")
    for cmd in sql_commands:
        try:
            cursor.execute(cmd)
        except oracledb.DatabaseError as e:
            error, = e.args
            # Ignorujeme chybu, pokud tabulka už existuje (abys to mohl pustit víckrát)
            if error.code == 955: 
                print(f"Info: Tabulka už existuje, přeskakuji.")
            else:
                print(f"Chyba u příkazu: {cmd[:50]}...")
                print(error.message)

    connection.commit()
    print("--- HOTOVO! Data jsou uložena. ---")

except Exception as e:
    print(f"Nastala chyba: {e}")
finally:
    if 'connection' in locals():
        connection.close()