import oracledb
from src.Core.Database import Database

def init_database():
    print("🚀 ZAHAJUJI KOMPLETNÍ RE-INSTALACI DATABÁZE...")
    
    try:
        db = Database()
        connection = db.connect()
        cursor = connection.cursor()
    except Exception as e:
        print(f"❌ Nelze se připojit k DB. Zkontroluj config/config.ini.\nChyba: {e}")
        return

    # ==========================================
    # 1. ÚKLID (DROP EVERYTHING)
    # ==========================================
    print("\n[1/5] Mažu staré tabulky a pohledy...")
    objects_to_drop = [
        ("VIEW", "V_ORDER_DETAILS"),
        ("VIEW", "V_ACTIVE_MATERIALS"),
        ("TABLE", "ORDERS"),       # Musí být první (FK)
        ("TABLE", "MATERIALS"),    # Musí být druhá (FK)
        ("TABLE", "CLIENTS"),
        ("TABLE", "CATEGORIES"),
        ("TABLE", "APP_LOGS")
    ]

    for obj_type, obj_name in objects_to_drop:
        try:
            cursor.execute(f"DROP {obj_type} {obj_name} CASCADE CONSTRAINTS")
            print(f"   - Smazáno: {obj_name}")
        except oracledb.DatabaseError as e:
            # Ignorujeme chybu, pokud objekt neexistuje (ORA-00942)
            error, = e.args
            if error.code != 942: 
                print(f"   ⚠️ Chyba při mazání {obj_name}: {e}")

    # ==========================================
    # 2. VYTVOŘENÍ TABULEK (DDL)
    # ==========================================
    print("\n[2/5] Vytvářím novou strukturu tabulek...")

    # A) CATEGORIES
    cursor.execute("""
        CREATE TABLE categories (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(100) NOT NULL,
            description VARCHAR2(255)
        )
    """)
    print("   - Vytvořeno: CATEGORIES")

    # B) CLIENTS
    cursor.execute("""
        CREATE TABLE clients (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            company_name VARCHAR2(150) NOT NULL,
            email VARCHAR2(100),
            credit_balance NUMBER(10, 2) DEFAULT 0
        )
    """)
    print("   - Vytvořeno: CLIENTS")

    # C) APP_LOGS
    cursor.execute("""
        CREATE TABLE app_logs (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            log_msg VARCHAR2(255),
            log_date DATE DEFAULT CURRENT_DATE
        )
    """)
    print("   - Vytvořeno: APP_LOGS")

    # D) MATERIALS (Vazba na Categories)
    cursor.execute("""
        CREATE TABLE materials (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR2(150) NOT NULL,
            price_per_kg NUMBER(10, 2) NOT NULL,
            hazard_level VARCHAR2(20) CHECK (hazard_level IN ('Low', 'Medium', 'High', 'Death')),
            is_active NUMBER(1) DEFAULT 1,
            category_id NUMBER,
            CONSTRAINT fk_mat_cat FOREIGN KEY (category_id) REFERENCES categories(id)
        )
    """)
    print("   - Vytvořeno: MATERIALS")

    # E) ORDERS (Vazba na Clients a Materials - M:N logika)
    cursor.execute("""
        CREATE TABLE orders (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            client_id NUMBER NOT NULL,
            material_id NUMBER NOT NULL,
            quantity NUMBER(10, 2) NOT NULL,
            total_price NUMBER(12, 2) NOT NULL,
            created_at DATE DEFAULT CURRENT_DATE,
            CONSTRAINT fk_ord_cli FOREIGN KEY (client_id) REFERENCES clients(id),
            CONSTRAINT fk_ord_mat FOREIGN KEY (material_id) REFERENCES materials(id)
        )
    """)
    print("   - Vytvořeno: ORDERS")

    # ==========================================
    # 3. VYTVOŘENÍ POHLEDŮ (VIEWS)
    # ==========================================
    print("\n[3/5] Vytvářím pohledy (Views)...")

    # View 1: Aktivní materiály
    cursor.execute("""
        CREATE OR REPLACE VIEW v_active_materials AS
        SELECT id, name, price_per_kg 
        FROM materials 
        WHERE is_active = 1
    """)
    print("   - Vytvořeno: V_ACTIVE_MATERIALS")

    # View 2: Detaily objednávek (JOIN)
    cursor.execute("""
        CREATE OR REPLACE VIEW v_order_details AS
        SELECT 
            o.id, 
            c.company_name AS client_name, 
            m.name AS material_name, 
            o.quantity, 
            o.total_price, 
            o.created_at
        FROM orders o
        JOIN clients c ON o.client_id = c.id
        JOIN materials m ON o.material_id = m.id
    """)
    print("   - Vytvořeno: V_ORDER_DETAILS")

    # ==========================================
    # 4. VLOŽENÍ ZÁKLADNÍCH DAT (SEED)
    # ==========================================
    print("\n[4/5] Vkládám testovací data...")

    # Kategorie (potřebujeme jejich ID pro materiály)
    cats = ["Běžný materiál", "Nebezpečný odpad", "Extrémně toxický", "Radioaktivní"]
    cat_ids = []
    
    # Použijeme RETURNING INTO pro získání ID
    id_var = cursor.var(int)
    for c_name in cats:
        cursor.execute("INSERT INTO categories (name) VALUES (:1) RETURNING id INTO :2", [c_name, id_var])
        cat_ids.append(id_var.getvalue()[0])
    
    id_bezny, id_nebezpecny, id_toxicky, id_radio = cat_ids
    print(f"   - Vloženo {len(cats)} kategorií.")

    # Materiály
    materials_data = [
        ("Štěrk", 50.0, "Low", id_bezny),
        ("Azbest", 500.0, "Medium", id_nebezpecny),
        ("Kyselina sírová", 1200.0, "High", id_nebezpecny),
        ("Plutonium-239", 950000.0, "Death", id_radio),
        ("Kryptonit", 50000.0, "High", id_toxicky),
        ("Voda z Fukušimy", 25.50, "Low", id_radio)
    ]
    cursor.executemany("""
        INSERT INTO materials (name, price_per_kg, hazard_level, category_id) 
        VALUES (:1, :2, :3, :4)
    """, materials_data)
    print(f"   - Vloženo {len(materials_data)} materiálů.")

    # Klienti
    clients_data = [
        ("Umbrella Corp.", "wesker@umbrella.com", 5000000),
        ("Stark Industries", "tony@stark.com", 99999999),
        ("Aperture Science", "glados@aperture.com", 15000),
        ("Black Mesa", "gordon@blackmesa.org", 500000)
    ]
    cursor.executemany("""
        INSERT INTO clients (company_name, email, credit_balance) 
        VALUES (:1, :2, :3)
    """, clients_data)
    print(f"   - Vloženo {len(clients_data)} klientů.")

    # ==========================================
    # 5. DOKONČENÍ
    # ==========================================
    connection.commit()
    connection.close()
    print("\n✅ HOTOVO! Databáze je kompletně připravena k použití.")

if __name__ == "__main__":
    init_database()